project_id = "cdrcyjrvurrphnceromd"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment-status]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.register-company]
verify_jwt = false

[functions.create-platform-fee-checkout]
verify_jwt = false

[functions.create-asaas-account]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.ticket-lookup]
verify_jwt = false

[functions.cleanup-expired-locks]
verify_jwt = false
