import { PAGBANK_API_BASE_URLS, PagbankError } from "./core.ts";
import { loadCurrentConnection, resolveCredentialFromConnection } from "./credentials.ts";

type RecordValue = Record<string, unknown>;
type Resource = "order" | "charge" | "order_by_charge" | "split";
type ProbeIds = { order_id?: unknown; charge_id?: unknown; split_id?: unknown; environment?: unknown };
const UUID = "[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}";
const STATUSES = new Set(["WAITING", "AUTHORIZED", "IN_ANALYSIS", "PAID", "DECLINED", "CANCELED"]);

function record(value: unknown): RecordValue {
  return value !== null && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : {};
}

function validId(value: unknown, prefix: string): value is string {
  return typeof value === "string" && new RegExp(`^${prefix}_${UUID}$`).test(value);
}

function summarize(data: unknown) {
  const root = record(data);
  const orders = (Array.isArray(data) ? data : Array.isArray(root.orders) ? root.orders : [root]).map(record);
  const charges = orders.flatMap((order) => Array.isArray(order.charges) ? order.charges.map(record) : []);
  const nodes = [root, ...orders, ...charges];
  const links = nodes.flatMap((node) => Array.isArray(node.links) ? node.links.map(record) : []);
  const splitLinks = links.filter((link) => String(link.rel).toUpperCase() === "SPLIT");
  const splitIds = nodes.map((node) => node.id).filter((id) => validId(id, "SPLI"));
  for (const link of splitLinks) {
    try {
      const url = new URL(String(link.href));
      const id = url.pathname.split("/").slice(-1)[0];
      if (url.origin === PAGBANK_API_BASE_URLS.sandbox && !url.username && !url.password && validId(id, "SPLI")) splitIds.push(id);
    } catch { /* Links não são seguidos nem retornados. */ }
  }
  const receivers = Array.isArray(root.receivers) ? root.receivers.map(record) : null;
  return {
    order_ids: [...new Set(nodes.map((node) => node.id).filter((id) => validId(id, "ORDE")))],
    charge_ids: [...new Set(nodes.map((node) => node.id).filter((id) => validId(id, "CHAR")))],
    split_ids: [...new Set(splitIds)],
    financial_statuses: [...new Set(nodes.map((node) => node.status).filter((status): status is string => typeof status === "string" && STATUSES.has(status)))],
    has_split_link: splitLinks.length > 0,
    receiver_count: receivers?.length ?? null,
    receiver_amounts: receivers?.map((receiver) => {
      const value = record(receiver.amount).value ?? receiver.amount;
      return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 ? value : null;
    }) ?? null,
  };
}

async function attempt(resource: Resource, path: string, accessToken: string) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20_000);
  try {
    const response = await fetch(`${PAGBANK_API_BASE_URLS.sandbox}${path}`, {
      method: "GET",
      headers: { Accept: "application/json", Authorization: `Bearer ${accessToken}` },
      redirect: "error",
      signal: controller.signal,
    });
    const text = await response.text();
    let data: unknown = null;
    try { data = text ? JSON.parse(text) : null; } catch { /* Só a classificação sanitizada sai do backend. */ }
    const isJsonObject = data !== null && typeof data === "object";
    const infraBlock = !response.ok && (/request blocked/i.test(text) || (!isJsonObject && /generated by cloudfront/i.test(text)));
    const errorCode = infraBlock ? "infra_block"
      : response.status === 401 ? "pagbank_unauthorized"
      : response.status === 403 ? "pagbank_forbidden"
      : response.status === 404 ? "pagbank_resource_not_found"
      : response.status === 406 ? "pagbank_not_acceptable"
      : !response.ok ? "pagbank_http_error"
      : !isJsonObject ? "pagbank_invalid_response" : null;
    return {
      resource, path, http_status: response.status, ok: response.ok && isJsonObject,
      response_origin: infraBlock ? "cloudfront" : isJsonObject ? "pagbank" : "unknown",
      error_code: errorCode,
      ...(response.ok && isJsonObject ? summarize(data) : {}),
    };
  } catch {
    return { resource, path, http_status: null, ok: false, response_origin: "network", error_code: "pagbank_unreachable" };
  } finally {
    clearTimeout(timeout);
  }
}

/** Somente a conexão corrente Connect SMS; não renova, escreve ou usa fallback. */
export async function probePagbankResources(
  supabaseAdmin: Parameters<typeof loadCurrentConnection>[0],
  params: { companyId: string; companyGateway: string; environment: string | null; ids: ProbeIds },
) {
  let credentialMode: string | null = null;
  const reject = (errorCode: string, status = 409) => ({ status, body: { ok: false, credential_mode: credentialMode, error_code: errorCode } });
  if (params.environment !== "sandbox" || (params.ids.environment != null && params.ids.environment !== "sandbox")) return reject("pagbank_environment_not_allowed");
  if (params.companyGateway !== "pagbank") return reject("pagbank_gateway_not_selected");

  const jobs: { resource: Resource; path: string }[] = [];
  for (const [field, prefix, path, resource] of [
    ["order_id", "ORDE", "orders", "order"],
    ["charge_id", "CHAR", "charges", "charge"],
    ["split_id", "SPLI", "splits", "split"],
  ] as const) {
    const value = params.ids[field];
    if (value == null) continue;
    const id = typeof value === "string" ? value.trim() : value;
    if (!validId(id, prefix)) return reject(`invalid_${field}`, 400);
    jobs.push({ resource, path: `/${path}/${encodeURIComponent(id)}` });
    if (field === "charge_id") jobs.push({ resource: "order_by_charge", path: `/orders?charge_id=${encodeURIComponent(id)}` });
  }
  if (!jobs.length) return reject("pagbank_resource_id_required", 400);

  try {
    const connection = await loadCurrentConnection(supabaseAdmin, { companyId: params.companyId, environment: "sandbox" });
    if (!connection) return reject("pagbank_connection_missing");
    credentialMode = connection.credential_mode;
    if (connection.company_id !== params.companyId || connection.gateway !== "pagbank" || connection.environment !== "sandbox") return reject("pagbank_tenant_mismatch");
    if (!connection.is_current || connection.status !== "connected" || !connection.access_token_enc) return reject("pagbank_connection_not_operational");
    if (credentialMode !== "connect_sms") return reject("pagbank_connection_not_homologated");
    let credential: Awaited<ReturnType<typeof resolveCredentialFromConnection>>;
    try {
      credential = await resolveCredentialFromConnection(supabaseAdmin, connection, "query", { allowRefresh: false });
    } catch (error) {
      if (error instanceof PagbankError && error.code === "pagbank_auth_failed") return reject("pagbank_credential_requires_refresh");
      return reject("pagbank_credential_unavailable");
    }
    const results = await Promise.all(jobs.map((job) => attempt(job.resource, job.path, credential.accessToken)));
    return { status: 200, body: { ok: results.every((result) => result.ok), credential_mode: credentialMode, results } };
  } catch {
    return reject("pagbank_connection_load_failed", 500);
  }
}
